### ISSUE TITLE
buoy brewing

### ISSUE THREAD

**Issue by sckott** [sckott/soylocs#100]
called, on hold for about 8 minutes, then they said they didn't have time to talk to me 

wow

**Comment by sckott** [comment]
fry: rice oil
sautee: olive oil
gluten free bread fine, need to check when we're there about cibatta bread (their most commonly used bread apparently)

Fressen Artisan Bakery listed in sources

@katherinehorn

**Comment by katherinehorn** [comment]
Fressen is fine. Ciabatta is almost always fine - i forget which bakery
it's from but if you can find that i can probably figure it out.

**Comment by sckott** [comment]
okay honey
