### ISSUE TITLE
Freshii (US Locations)

### ISSUE THREAD

**Issue by katherinehorn** [sckott/soylocs#137]
I need to avoid: 
Tortilla wraps 
Energii Bites
Peanut Sauce 
Scrambled Eggs

**Comment by sckott** [comment]
okay will do honey

**Comment by sckott** [comment]
which ones should i put on the map?

**Comment by katherinehorn** [comment]
Not sure... the Portland ones at least?

On Fri, Jul 14, 2017 at 1:44 PM, Scott Chamberlain <notifications@github.com

**Comment by katherinehorn** [comment]
And maybe Chicago (downtown) and Denver if they have them there? Since I go
there for work.

**Comment by sckott** [comment]
they don't have any in Colorado
