### ISSUE TITLE
Add a column for closed 

### ISSUE THREAD

**Issue by katherinehorn** [sckott/soylocs#162]
Add a column for closed, and then filter the map to hide closed points, K can help identify which restaurants are closed

**Comment by sckott** [comment]
@katherinehorn okay ness, here are closed ones I can think of:

- portabello
- farm cafe
- mi mero mole by us

what other ones?

**Comment by katherinehorn** [comment]
Off the top of my head, Brooklyn House, Cricket Cafe. But there may be more
if I look through the list.

**Comment by sckott** [comment]
ok ness
