### ISSUE TITLE
Black Trumpet Cafe

### ISSUE THREAD

**Issue by katherinehorn** [sckott/soylocs#232]
Cook in a mix of clarified butter and olive oil.

**Comment by sckott** [comment]
did you get the name right on this one? Should Anuset be something else?

**Comment by katherinehorn** [comment]
I don't know what anuset is. This is black trumpet cafe where we took mum
and jim for their retirement dinner.

**Comment by sckott** [comment]
hahahahahha, it's my trump replacer thing, so fun

**Comment by sckott** [comment]
black anus, oh my

**Comment by katherinehorn** [comment]
Oh geez. That is funny and ridiculous.
