### ISSUE TITLE
More things to add (all have soy free stuff)

### ISSUE THREAD

**Issue by katherinehorn** [sckott/soylocs#36]
Suzette Creperie - cook in canola and olive, bread is from Portland French and it doesn’t have oil (I would double check when there though)
Ankeny Tap and Table - olive and canola blend, some bread is Grand Central, some Portland French
Andina - olive, some canola, no soy (they specifically said!!)
Accanto - olive oil, but fryer is soy
MeKha Grill - uses canola
Tao of Tea - canola olive blend, and then some stuff is packaged but they know the ingredients, so I would just need to ask

**Comment by sckott** [comment]
:turtle:

**Comment by katherinehorn** [comment]
You're really more of a rabbit than a turtle!

**Comment by sckott** [comment]
:rabbit:

**Comment by sckott** [comment]
:rabbit2:

**Comment by katherinehorn** [comment]
Ahem... 7 days.

**Comment by sckott** [comment]
well the 48 in 48 hours is a bigger number than 7 in 7 days, so there
