### ISSUE TITLE
Soy results

### ISSUE THREAD

**Issue by katherinehorn** [sckott/soylocs#38]
Horn of Africa - olive and canola for saute, soybean oil to deep fry so no donuts for me
Bipartisan Cafe - baked goods from scratch with real butter, would need to ask more questions there
Toast - canola and grapeseed, scones are butter, but english muffins are vegetable oil (seems strange, confirm when there)

**Comment by sckott** [comment]
okay honay

**Comment by katherinehorn** [comment]
Ahem... 5 days. ;-)

**Comment by katherinehorn** [comment]
Also, please add Paper Bag Pizza - sauteeing oil is canola/olive blend. No oil in sauce or dough.

**Comment by sckott** [comment]
OMG, im like totally busy and stuff, OMG, like totally
