### ISSUE TITLE
Pine Street

### ISSUE THREAD

**Issue by katherinehorn** [sckott/soylocs#40]
Update Pfriem description to: uses rice bran oil, most things made in house (including aioli from scratch), some bread is from Pine Street Bakery (which is soy-free), other things they don't make in house they should have ingredient info for

Pine Street Bakery: No soy in breads, use canola/olive blend for cooking, pastries are with real butter. Remaining question would be do they make their own dressings?

**Comment by sckott** [comment]
cutie

**Comment by katherinehorn** [comment]
Thanks

**Comment by katherinehorn** [comment]
Cough cough - time's a ticking. :)

**Comment by sckott** [comment]
doing it honey
