### ISSUE TITLE
pambiche is duplicated, retain just one

### ISSUE THREAD

**Issue by sckott** [sckott/soylocs#41]

**Comment by sckott** [comment]
called
- fryer is rice oil
- sauteeing, asked and they said olive oil. I said that seems surprising, but they said yes, olive oil. 
- no soy in empanadas

**Comment by katherinehorn** [comment]
Olive oil makes sense for sautee. It only doesn't make sense for deep fry. And their empanadas (thanks for asking) are made with lard... but I might eat them anyway. :)  Did you happen to ask if their breads are made in house? If not, I can ask when we go and if they don't know ingredients it'll be something to research for next time.

**Comment by sckott** [comment]
i didn't think about breads, but yeah, we can ask when we get there
