### ISSUE TITLE
Astoria Restaurants

### ISSUE THREAD

**Issue by katherinehorn** [sckott/soylocs#43]
Himani Indian cuisine - Canola oil
Street 14 Cafe - either rice bran oil or olive oil, all baked goods in house and they can answer ingredient questions - they were super helpful !
Fort George Brewery - all cooking in canola oil, and and breads and pizza dough are made in house, would want to double check on specific items when I’m there though

**Comment by katherinehorn** [comment]
Bridgewater Bistro: Pretty sure cooking oil is canola, but need to confirm (phone person was not good at getting answers), breads are sunflower oil or no oil at all

**Comment by sckott** [comment]
thanks honey!

**Comment by katherinehorn** [comment]
Blue Scorcher Cafe - they don’t use soy at all, other than tempeh and soy milk for coffee, oils are olive oil or sunflower seed oil
Columbian Cafe - olive and canola oil only
