### ISSUE TITLE
city state

### ISSUE THREAD

**Issue by sckott** [sckott/soylocs#46]
- what oil/etc. they cook with: 
  - fry: canola (Asked twice about this to make sure)
  - sautee:  canola
- portland french bakery (will call)
  - toast - they make in house - no soy oils or flours
  - english muffin - they don't make in house - does have soy flour and soy oil, stay away from honey
- made in house
  - biscuits
  - scones
  - coffee cake
  - cookies

**Comment by katherinehorn** [comment]
And??? I am eagerly awaiting the verdict! 

Also, I think the most likely not in house baked items are the toast and english muffins, it seemed from the website that they do the scones, coffee cake, and biscuits in house, but i could be wrong.

**Comment by sckott** [comment]
i am going there tomorrow morning to ask in person b/c there's lots of questions, and too important to deal with some impatient person over the phone

**Comment by katherinehorn** [comment]
Gosh, I hope that's not a pain! I guess if I can't eat there, at least you can get a scone or something so your trip isn't a waste?

**Comment by sckott** [comment]
its just easier to get the right person that knows stuff If im there, yes, scone bueno mouth food

**Comment by sckott** [comment]
called waiting to hear back on english muffins cause they don't even make them, they buy from another bakery

**Comment by katherinehorn** [comment]
Weird. Well it will be a good mystery to work out. I'm guessing they will
have soy, but at least there are biscuits!

**Comment by sckott** [comment]
they said they use a highly refined soy oil at the bakery, which he says removes all allergens, so even if a product has a soy oil, it _MAY_ be okay

**Comment by katherinehorn** [comment]
Nope. Not okay for me. Okay if you are allergic to soy protein.

**Comment by sckott** [comment]
i heard back honey see up above https://github.com/sckott/soylocs/issues/46#issue-143325387
