### ISSUE TITLE
So Cool!

### ISSUE THREAD

**Issue by jhollist** [sckott/soylocs#6]
Sorry to clutter your issues @sckott, but wanted to say this is a great idea.  

My son has a peanut and tree-nut allergy and finding safe and knowledgeable restaurants can be a challenge.  We essentially have our few that we got back to.  I might start a similar thing back east.

Thanks for the inspiration and good luck building the list!

**Comment by sckott** [comment]
thanks @jhollist !  Im not hadley, so i don't think my issues will ever be cluttered :)

Sorry to hear about his allergy!  It's my wife that has the allergy - I thought I would make this to keep track of where we can and can't eat.  

It can surely be better, but serves purpose 

Looking forward to yours
