### ISSUE TITLE
Portland, ME and Dover, NH Restaurants

### ISSUE THREAD

**Issue by katherinehorn** [sckott/soylocs#78]
Duckfat - fry in duckfat/canola mix, olive oil in other dishes
Holy Donut (2 locations) - fry in canola
Local 188 - uses soybean oil in most dishes
Flatbread Company (Portland, ME) - no soybean oil used in dough, sauce, dressings, saute, etc.

Sonny's (Dover) - sunflower oil to fry; oil for saute, salad, and mayo a blend containing soybean oil so need to special request soy-free dishes

**Comment by sckott** [comment]
thanks honey

**Comment by sckott** [comment]
did it honey 🐨
